name: PHP Tests

on: [ push, pull_request ]

jobs:

  build_app:
    name: "PHP CS Fixer"
    runs-on: ubuntu-latest

    steps:

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: cs2pr, php-cs-fixer

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run
        run: |
          php-cs-fixer fix --dry-run --diff
          php-cs-fixer fix --rules=@PER-CS2.0 --allow-risky=yes --verbose --show-progress=dots --dry-run
          php-cs-fixer fix --rules=@PER-CS2.0 --allow-risky=yes --verbose --show-progress=dots


  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        php: [ '8.1', '8.2', '8.3', '8.4' ]

    name: PHP ${{ matrix.php }} on ${{ matrix.os }}
    steps:

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer run-script test

